name: Generate changelog

on:
    push:

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Get Date
              id: get-date
              run: |
                echo "::set-output name=date::$(/bin/date -u "+%s")"
              shell: bash
            - uses: actions/cache@v2
              with:
                path: ~/repos
                key: bare-repos-${{ steps.get-date.outputs.date }}
                restore-keys: bare-repos-
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyyaml
            - run: ls -lart ~/repos || echo "no repos"
            - run: python git_changelog.py
            - run: pwd
            - run: ls -lart ~/repos
