name: Generate changelog

on:
    push:

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - run: ls -lart /repos || echo "no repos"
            - run: python git_changelog.py
            - run: pwd
            - run: ls -lart /repos
